heartbeat.monitors:
- type: http
  schedule: '@every 10s'
  urls:
    - https://fatmali@github.io
    - https://google.com

  check.request:
    method: GET
    headers:
        'Content-Type': 'application/json' 
  check.response:
       status: 200
       

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "kibana:5601"
